
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class Janela1:
    def __init__(self):
        self.window = Tk()

        self.window.geometry("1000x650")
        self.window.configure(bg = "#FFFFFF")


        self.canvas = Canvas(
            self.window,
            bg = "#FFFFFF",
            height = 650,
            width = 1000,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            499.5,
            235.0,
            image=self.entry_image_1
        )
        self.entry_1 = Entry(
            bd=0,
            bg="#1D4E00",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(
            x=84.0,
            y=191.0,
            width=831.0,
            height=86.0
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            499.5,
            523.0,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(
            bd=0,
            bg="#1D4E00",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=84.0,
            y=479.0,
            width=831.0,
            height=86.0
        )

        self.canvas.create_text(
            84.0,
            138.0,
            anchor="nw",
            text="Informe o seu nome:",
            fill="#000000",
            font=("InknutAntiqua Bold", 24 * -1)
        )

        self.canvas.create_text(
            84.0,
            282.0,
            anchor="nw",
            text="Informe a sua idade:",
            fill="#000000",
            font=("InknutAntiqua Bold", 24 * -1)
        )

        self.canvas.create_text(
            213.0,
            496.0,
            anchor="nw",
            text="Olá “nome”, você tem “idade” anos",
            fill="#000000",
            font=("InknutAntiqua Bold", 24 * -1)
        )

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        self.entry_bg_3 = self.canvas.create_image(
            499.5,
            379.0,
            image=self.entry_image_3
        )
        self.entry_3 = Entry(
            bd=0,
            bg="#1D4E00",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_3.place(
            x=84.0,
            y=335.0,
            width=831.0,
            height=86.0
        )

        self.canvas.create_rectangle(
            0.0,
            0.0,
            1000.0,
            88.0,
            fill="#01004E",
            outline="")
        self.window.resizable(False, False)
        self.window.mainloop()


class Janela2:
    def __init__(self):
        self.window = Tk()

        self.window.geometry("1000x650")
        self.window.configure(bg="#FFFFFF")

        self.canvas = Canvas(
            self.window,
            bg="#FFFFFF",
            height=650,
            width=1000,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        self.canvas.place(x=0, y=0)
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            499.5,
            235.0,
            image=self.entry_image_1
        )
        self.entry_1 = Entry(
            bd=0,
            bg="#1D4E00",
            fg="#000716",
            highlightthickness=0,
            font=("Times New Roman", 25),
        )
        self.entry_1.place(
            x=84.0,
            y=191.0,
            width=831.0,
            height=86.0,
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            499.5,
            523.0,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(
            bd=0,
            bg="#1D4E00",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=84.0,
            y=479.0,
            width=831.0,
            height=86.0
        )

        self.canvas.create_text(
            84.0,
            138.0,
            anchor="nw",
            text="Informe o seu nome:",
            fill="#000000",
            font=("InknutAntiqua Bold", 24 * -1)
        )

        self.canvas.create_text(
            84.0,
            282.0,
            anchor="nw",
            text="Informe a sua idade:",
            fill="#000000",
            font=("InknutAntiqua Bold", 24 * -1)
        )

        self.canvas.create_text(
            213.0,
            496.0,
            anchor="nw",
            text="Olá “nome”, você tem “idade” anos",
            fill="#000000",
            font=("InknutAntiqua Bold", 24 * -1)
        )

        self.canvas.create_rectangle(
            0.0,
            0.0,
            1000.0,
            88.0,
            fill="#01004E",
            outline="")
        self.window.resizable(False, False)
        self.window.mainloop()
